### PR TITLE
gosnmp.go: Deprecate math/rand

### LINKED ISSUE #267: Use crypto/rand in gosnmp.go
golangci-lint error:

```
gosnmp.go:261:14: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
		x.random = rand.New(rand.NewSource(time.Now().UTC().UnixNano()))
```

### PR DESCRIPTION
**Pull request by TimRots**
Deprecate ``math/rand`` in favor of ``crypto/rand``

Fixes #267

Signed-off-by: Tim Rots <tim.rots@protonmail.ch>

### CODE REVIEW

File: gosnmp.go [hunk 1]
```diff
@@ -252,27 +252,23 @@ func (x *GoSNMP) connect(networkSuffix string) error {
...
-	if err != nil {
+	if err = x.netConnect(); err != nil {
 		return fmt.Errorf("error establishing connection to host: %s", err.Error())
 	}
 
-	if x.random == nil {
-		// TODO: https://github.com/gosnmp/gosnmp/issues/267
-		x.random = rand.New(rand.NewSource(time.Now().UTC().UnixNano())) //nolint:gosec
+	if x.random == 0 {
+		n, err := rand.Int(rand.Reader, big.NewInt(2147483647)) // returns a uniform random value in [0, 2147483647].
```
Comment (SuperQ) [inline gosnmp.go:260]: Maybe use the `math.MaxInt32` constant?

**Review by SuperQ — COMMENTED** [review]
Minor nit about the max range, but otherwise LGTM.

File: gosnmp.go (hunk 1 above)
Comment (TimRots) [reply gosnmp.go:260]: Good one, will update PR.

**Comment by TimRots** [comment]
> Minor nit about the max range, but otherwise LGTM.

Good one, updated the PR with your suggestion.

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by SuperQ — APPROVED** [review]
LGTM
