### PR TITLE
marshal.go: improve packet validation and error handling

### LINKED ISSUE #311: unmarshalPayload: index out of range (v1.29.0)
Hey, first thanks for the work on gosnmp !

I'm seeing the following error using v1.29.0

Snmp version: 3
Device Type: APC UPS (sysobjectid: 1.3.6.1.4.1.318.1.3.27)

```
runtime error: index out of range [0] with length 0
Stack:goroutine 291 [running]:
github.com/gosnmp/gosnmp.(*GoSNMP).send.func1(0xc000a3b2b0)
	.../github.com/gosnmp/gosnmp@v1.29.0/marshal.go:326 +0xa1
panic(0x3e23c20, 0xc00126dfe0)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/runtime/panic.go:969 +0x166
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalPayload(0xc000920240, 0x0, 0x0, 0x0, 0x0, 0xc000789260, 0x0, 0x0)
	.../github.com/gosnmp/gosnmp@v1.29.0/marshal.go:872 +0x536
github.com/gosnmp/gosnmp.(*GoSNMP).sendOneRequest(0xc000920240, 0xc00087c460, 0x1, 0x0, 0xe0, 0x3f91980)
	.../github.com/gosnmp/gosnmp@v1.29.0/marshal.go:269 +0x7cd
github.com/gosnmp/gosnmp.(*GoSNMP).send(0xc000920240, 0xc00087c460, 0xc0012c6001, 0x0, 0x0, 0x0)
	.../github.com/gosnmp/gosnmp@v1.29.0/marshal.go:349 +0xef
github.com/gosnmp/gosnmp.(*GoSNMP).Get(0xc000920240, 0xc00035e780, 0x27, 0x28, 0x1, 0x1882910, 0xc00027ab40)
	.../github.com/gosnmp/gosnmp@v1.29.0/gosnmp.go:363 +0x154
```

Seems raised by this line: https://github.com/gosnmp/gosnmp/blob/bd1d291881777450abc4399ee2fd0bb2795eb18b/marshal.go#L872

With `unmarshalPayload` being called with empty list of `packet` and cursor being `0`.

It looks like we don't handle errors here if `decryptPacket` returns an error:
https://github.com/gosnmp/gosnmp/blob/bd1d291881777450abc4399ee2fd0bb2795eb18b/marshal.go#L266

I will try to get an example payload triggering this issue and share it here.

### PR DESCRIPTION
**Pull request by TimRots**
* marshal.go: Add error handling to decryptPacket call in sendOneRequest()
* marshal.go: Add empty/nil packet validation to unmarshalPayload()

Fixes #311

Signed-off-by: Tim Rots <tim.rots@protonmail.ch>

### CODE REVIEW

File: marshal.go [hunk 1]
```diff
@@ -976,24 +980,31 @@ func (x *GoSNMP) unmarshalHeader(packet []byte, response *SnmpPacket) (int, erro
 }
 
 func (x *GoSNMP) unmarshalPayload(packet []byte, cursor int, response *SnmpPacket) error {
-	var err error
+	if packet == nil || (bytes.Equal(packet, []byte{}) && cursor == 0) {
```
Comment (AlexandreYang) [inline marshal.go:983]:
```suggestion
	if len(packet) == 0 {
```

Maybe checking `len(packet) == 0` could be enough ? since both nil and empty list will lead to `0`

Any reason to check `cursor == 0` too ? It seems that `requestType := PDUType(packet[cursor])` will fail in any case if packet is empty/nil.

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by AlexandreYang — COMMENTED** [review]
Thanks for the PR 👍 

Just have a minor comment.

**Review by AlexandreYang — APPROVED** [review]

File: marshal.go (hunk 1 above)
Comment (TimRots) [reply marshal.go:983]: Thanks for checking the PR Alexandre. 
Ran some tests and you are right, we can reduce the packet validation to ``len(packet) == 0`` here.
Will update the PR accordingly.
